import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'

const mdPath = path.resolve('docs/colors.md')
const outputPath = './src/components/00-foundations'

// 1. Read markdown file
const markdown = readFileSync(mdPath, 'utf-8')

// 2. Extract table rows (skip first two lines: header & separator)
const lines = markdown.split('\n').filter((line) => line.trim().startsWith('|'))

const rows = lines.slice(2) // skip table header + --- separator

// 3. Build MDX table rows
const tableRows = rows
  .map((line) => {
    const value = line
      .split('|')
      .map((c) => c.trim())
      .filter((_, index) => index === 3)[0]

    return `
      <tr>
        <td>${value}</td>
        <td>
          <div style={{
            width: '4rem',
            height: '4rem',
            backgroundColor: \`var(${value.replace(/`/g, '')})\`,
            border: '1px solid #ccc'
          }}/>
        </td>
      </tr>
    `
  })
  .join('\n')

const mdxContent = `
import { Meta, Title, Subtitle } from '@storybook/blocks'

<Meta title="Foundation/Colors" />

<Title>Colors</Title>

{/**
 * --------------------------------------------------------------------
 * THIS FILE IS AUTO-GENERATED — DO NOT EDIT IT DIRECTLY!
 *
 * This file was generated by the colors/generate-mdx script.
 * Any manual changes will be overwritten.
 *
 * To update this file, run the appropriate generation script.
 * The script is automatically triggered by the pre-flight script
 * --------------------------------------------------------------------
 */}

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Preview</th>
    </tr>
  </thead>
  <tbody>
    ${tableRows}
  </tbody>
</table>
`

mkdirSync(outputPath, { recursive: true })
writeFileSync(`${outputPath}/colors.mdx`, mdxContent)
console.log(`✅ Generated Storybook MDX: ${outputPath}/colors.mdx`)
