import colors from 'material-colors'
import { writeFileSync } from 'node:fs'

const cssVarsArr: string[] = []

function toShortHex(hex: string): string {
  const cleanHex = hex.replace(/^#/, '').toLowerCase()

  if (
    cleanHex.length === 6 &&
    cleanHex[0] === cleanHex[1] &&
    cleanHex[2] === cleanHex[3] &&
    cleanHex[4] === cleanHex[5]
  ) {
    return '#' + cleanHex[0] + cleanHex[2] + cleanHex[4]
  }

  return hex.startsWith('#') ? hex : '#' + hex
}

Object.entries(colors).forEach(([colorName, shades]) => {
  if (typeof shades === 'object') {
    Object.entries(shades as object)
      .filter(([shade]) => !Number.isNaN(Number(shade)))
      .forEach(([shade, value]) => {
        cssVarsArr.push(`\t--neo-color-${colorName}-${shade}: ${toShortHex(value)};`)
      })
  } else if (typeof shades === 'string') {
    cssVarsArr.push(`\t--neo-color-${colorName}: ${toShortHex(shades)};`)
  }
})

const cssVars = cssVarsArr.join('\n')

writeFileSync(
  './src/assets/styles/colors.css',
  `/**
 * --------------------------------------------------------------------
 * THIS FILE IS AUTO-GENERATED — DO NOT EDIT IT DIRECTLY!
 *
 * This file was generated by the colors/generate-css script.
 * Any manual changes will be overwritten.
 *
 * To update this file, run the appropriate generation script.
 * --------------------------------------------------------------------
 */
\n:root {\n${cssVars}\n}\n`,
)

console.log('✅ colors.css generated')
