import colors from 'material-colors'
import { writeFileSync } from 'node:fs'

const cssVarsArr: string[] = []

Object.entries(colors).forEach(([colorName, shades]) => {
  if (typeof shades === 'object') {
    Object.entries(shades as object)
      .filter(([shade]) => !Number.isNaN(Number(shade)))
      .forEach(([shade, value]) => {
        cssVarsArr.push(`--neo-color-${colorName}-${shade}: ${value};`)
      })
  } else if (typeof shades === 'string') {
    cssVarsArr.push(`--neo-color-${colorName}: ${shades};`)
  }
})

const cssVars = cssVarsArr.join('\n')

writeFileSync(
  './src/assets/styles/colors.css',
  `/**
 * --------------------------------------------------------------------
 * THIS FILE IS AUTO-GENERATED — DO NOT EDIT IT DIRECTLY!
 *
 * This file was generated by the colors/generate-css script.
 * Any manual changes will be overwritten.
 *
 * To update this file, run the appropriate generation script.
 * --------------------------------------------------------------------
 */
\n:root {\n${cssVars}\n}\n`,
)

console.log('✅ colors.css generated')
