services:
  storybook:
    build:
      context: .
      dockerfile: docker/DOCKERFILE.storybook
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    container_name: neo-materia-storybook

  tests:
    build:
      context: .
      dockerfile: docker/DOCKERFILE.test
    volumes:
      - .:/app
      - /app/node_modules
    container_name: neo-materia-tests
