FROM node:22-alpine

WORKDIR /app

COPY package*.json ./
RUN HUSKY=0 npm ci

COPY . .

RUN npm run type-check

RUN npm run lint:fix

RUN npm run stylelint:css

RUN npm run prettier:fix

RUN mkdir -p /root/.storybook && \
    echo '{"version":1,"checklist":{"widget":{"disable":true}}}' > /root/.storybook/settings.json

EXPOSE 3000
CMD ["npm", "run", "storybook"]
