FROM node:20-alpine

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .

RUN npm run type-check

RUN npm run lint:fix

RUN npm run stylelint:css

RUN npm run prettier:fix

CMD ["npm", "run", "test:unit"]
