// scripts/generate-globals-css.ts
import { writeFileSync, readdirSync } from 'node:fs'
import { join } from 'node:path'

const mixinsDir = join(process.cwd(), './src/assets/styles/mixins')
const stylesDir = join(process.cwd(), './src/assets/styles')
const outputFile = join(stylesDir, 'globals.css')

const mixins = readdirSync(mixinsDir)
const cssMixinFiles = mixins.filter((f) => f.endsWith('.css'))
let imports = cssMixinFiles.map((file) => `@import url('./mixins/${file}');`).join('\n')

const styles = readdirSync(stylesDir)
const cssFiles = styles.filter((f) => f.endsWith('.css') && f !== 'globals.css')

// Generate import statements relative to globals.css
imports += `\n${cssFiles.map((file) => `@import url('./${file}');`).join('\n')}`

writeFileSync(
	outputFile,
	`/**
 * --------------------------------------------------------------------
 * THIS FILE IS AUTO-GENERATED — DO NOT EDIT IT DIRECTLY!
 *
 * This file was generated by the generate-globals script.
 * Any manual changes will be overwritten.
 *
 * To update this file, run the appropriate generation script.
 * The script is automatically triggered by the pre-flight script
 * --------------------------------------------------------------------
 */\n${imports}\n`,
)
console.log('✅ globals.css generated with imports:\n', imports)
