// scripts/generate-globals-css.ts
import { writeFileSync, readdirSync } from 'node:fs'
import { join } from 'node:path'

const assetsDir = join(process.cwd(), './src/assets/styles')
const outputFile = join(assetsDir, 'globals.css')

// Read all files in src/assets
const files = readdirSync(assetsDir)

// Filter CSS files excluding globals.css itself
const cssFiles = files.filter((f) => f.endsWith('.css') && f !== 'globals.css')

// Generate import statements relative to globals.css
const imports = cssFiles.map((file) => `@import './${file}';`).join('\n')

writeFileSync(
  outputFile,
  `/**
 * --------------------------------------------------------------------
 * THIS FILE IS AUTO-GENERATED — DO NOT EDIT IT DIRECTLY!
 *
 * This file was generated by the generate-globals script.
 * Any manual changes will be overwritten.
 *
 * To update this file, run the appropriate generation script.
 * The script is automatically triggered by the pre-flight script
 * --------------------------------------------------------------------
 */\n${imports}\n`,
)
console.log('✅ globals.css generated with imports:\n', imports)
