import colorsRaw from 'material-colors'
import { mkdirSync, writeFileSync } from 'node:fs'
import { runScript } from './utils/script-helper'
import { toShortHex } from './utils/css-helper'
import { dirname, join } from 'node:path'
import { toPascalCase } from '../src/utils/stringManipulation'
import { isAccessible } from '../src/utils/wcag'
import { shouldSkipGeneration, updateCache } from './utils/cache-helper'

const SCRIPT_NAME = 'generate-colors'
const SOURCE_FILES = ['scripts/generate-colors.ts', 'node_modules/material-colors/dist/colors.json']
const OUTPUT_FILES = [
	'src/assets/typescript/colors.ts',
	'src/assets/styles/colors.css',
	'docs/colors.md',
	'src/components/00-foundations/colors.mdx',
]

// Check if we can skip generation
if (shouldSkipGeneration(SCRIPT_NAME, SOURCE_FILES, OUTPUT_FILES)) {
	process.exit(0)
}

const specialColors: ColorName[] = []

/**
 * Generate TS file
 */

const flatColors: Record<string, string> = {}

Object.entries(colorsRaw).forEach(([colorName, shades]) => {
	if (typeof shades === 'object') {
		Object.entries(shades as object).forEach(([shade, value]) => {
			// Only use numeric shades, skip non-numeric (like "A100") if you want or keep all keys
			if (!Number.isNaN(Number(shade))) {
				const key = `${colorName}-${shade}`
				flatColors[key] = value as string
			}
		})
	} else if (typeof shades === 'string') {
		flatColors[colorName] = shades
	}
})

const colorNames: string[] = Object.keys(flatColors)
	.map((color) => color.split('-')[0])
	.reduce((result: string[], current) => {
		if (!result.includes(current)) {
			result.push(current)
		}
		return result
	}, [])

// Generate color family names (without shade numbers) - excluding special colors
const colorFamilies = colorNames.filter((name) => !specialColors.includes(name))

const tsContent = `/**
 * --------------------------------------------------------------------
 * THIS FILE IS AUTO-GENERATED — DO NOT EDIT IT DIRECTLY!
 *
 * This file was generated by the generate-colors script.
 * Any manual changes will be overwritten.
 * --------------------------------------------------------------------
 */

/**
 * array for all possible colors names (including special colors)
*/
export const colorNames = \n${JSON.stringify(colorNames, null, 2)} as const

/**
 * array for color families (without shade numbers)
 * Users specify these, and CSS handles the specific shade (500 by default)
*/
export const colors = \n${JSON.stringify(colorFamilies, null, 2)} as const

/**
 * type that define all colors available for components
 * Only color families are exposed (e.g., "blue", "green", not "blue500")
*/
export type Color = typeof colors[number]

/**
 * object of all possible color values with shades
 * Internal use only - for CSS generation
*/
export const colorsFlat = ${JSON.stringify(flatColors, null, 2)}
`

writeFileSync('src/assets/typescript/colors.ts', tsContent)

console.log('✅ colors.ts generated')

runScript('npx prettier --write src/assets/typescript/colors.ts')

/**
 * Generate CSS file
 */

// CSS colors
const cssVarsArr: string[] = []

Object.entries(flatColors).forEach(([colorName, value]) => {
	cssVarsArr.push(`\t--neo-color-${colorName.replace('-', '')}: ${toShortHex(value)};`)
})

const cssVars = cssVarsArr.join('\n')

// Generate themed CSS classes for color families only (not individual shades)
// Strategy: Each color family gets ONE CSS class (e.g., .Themed--blue)
// We start with shade 500 and adjust to ensure white/black text is accessible
const themedClasses: string[] = []
const processedFamilies = new Set<string>()

Object.entries(flatColors).forEach(([colorName]) => {
	const [family, shade] = colorName.split('-')

	// Only process shade 500 for regular colors (or no shade for special colors like white/black)
	if (shade !== '500' && shade !== undefined) {
		return
	}

	// Skip if we've already processed this family
	if (processedFamilies.has(family)) {
		return
	}
	processedFamilies.add(family)

	// Exception: Some colors can't support white text at any shade
	// For these, we use black text in light mode for accessibility
	const blackTextExceptions = ['yellow', 'amber', 'orange', 'white']
	const usesBlackTextInLightMode = blackTextExceptions.includes(family)

	// LIGHT MODE: --neo-theme-color (background with white/black text ON it)
	let lightModeColorVar = shade ? `${family}${shade}` : family
	let lightModeAccessible = false

	if (usesBlackTextInLightMode) {
		// For yellow/amber/orange: find a shade where black text is accessible
		// Start with 500, go lighter (400, 300, 200) if needed
		const lightModeShades = ['500', '400', '300', '200', '100']

		for (const testShade of lightModeShades) {
			const testKey = `${family}-${testShade}`
			if (flatColors[testKey]) {
				const testBg = toShortHex(flatColors[testKey])
				// Check if black text is accessible ON this shade
				if (isAccessible(testBg, '#000000')) {
					lightModeColorVar = `${family}${testShade}`
					lightModeAccessible = true
					break
				}
			}
		}
	} else {
		// Normal colors: find a shade where white text is accessible
		// Start with 500, go darker (600, 700) if needed
		const lightModeShades = ['500', '600', '700', '800', '900']

		for (const testShade of lightModeShades) {
			const testKey = `${family}-${testShade}`
			if (flatColors[testKey]) {
				const testBg = toShortHex(flatColors[testKey])
				// Check if white text is accessible ON this shade
				if (isAccessible(testBg, '#ffffff')) {
					lightModeColorVar = `${family}${testShade}`
					lightModeAccessible = true
					break
				}
			}
		}
	}

	// Fallback: if no shade is accessible, use the best available
	if (!lightModeAccessible) {
		const fallbackShade = usesBlackTextInLightMode
			? ['100', '200', '300', '400', '500'].find(
					(testShade) => flatColors[`${family}-${testShade}`],
				)
			: ['900', '800', '700', '600', '500'].find(
					(testShade) => flatColors[`${family}-${testShade}`],
				)

		if (fallbackShade) {
			lightModeColorVar = `${family}${fallbackShade}`
			console.warn(
				`⚠️  Warning: ${family} cannot achieve WCAG AA contrast. Using ${family}${fallbackShade} as best effort.`,
			)
		}
	}

	// DARK MODE: --neo-theme-color (background with black text ON it)
	// Start with 500, go lighter (400, 300, 200) if black text isn't accessible
	const darkModeShades = ['500', '400', '300', '200', '100']
	let darkModeColorVar = shade ? `${family}${shade}` : family
	let darkModeAccessible = false

	for (const testShade of darkModeShades) {
		const testKey = `${family}-${testShade}`
		if (flatColors[testKey]) {
			const testBg = toShortHex(flatColors[testKey])
			// Check if black text is accessible ON this shade
			if (isAccessible(testBg, '#000000')) {
				darkModeColorVar = `${family}${testShade}`
				darkModeAccessible = true
				break
			}
		}
	}

	// Fallback: if no shade is accessible with black text, use the lightest available (best effort)
	if (!darkModeAccessible) {
		const lightestShade = ['100', '200', '300', '400', '500'].find(
			(testShade) => flatColors[`${family}-${testShade}`],
		)
		if (lightestShade) {
			darkModeColorVar = `${family}${lightestShade}`
			console.warn(
				`⚠️  Warning: ${family} cannot achieve WCAG AA contrast with black text in dark mode. Using ${family}${lightestShade} as best effort.`,
			)
		}
	}

	// LIGHT MODE: --neo-theme-colorAccessible (text/border color ON light page background)
	// For exception colors (yellow/amber/orange), use the darkest shade or black
	// For regular colors, start with 700, go darker (800, 900) or lighter (600, 500)
	let accessibleLightColorVar = lightModeColorVar

	if (usesBlackTextInLightMode) {
		// For yellow/amber/orange, even the darkest shade may not achieve WCAG AA on white
		// Try darkest shades first, fallback to using the color with reduced opacity or black
		const darkestShades = ['900', '800', '700']
		let found = false

		for (const testShade of darkestShades) {
			const testKey = `${family}-${testShade}`
			if (flatColors[testKey]) {
				const testColor = toShortHex(flatColors[testKey])
				if (isAccessible('#ffffff', testColor)) {
					accessibleLightColorVar = `${family}${testShade}`
					found = true
					break
				}
			}
		}

		// If no shade is accessible, use the darkest available (best effort)
		if (!found) {
			const darkestAvailable = darkestShades.find((shade) => flatColors[`${family}-${shade}`])
			if (darkestAvailable) {
				accessibleLightColorVar = `${family}${darkestAvailable}`
				console.warn(
					`⚠️  Warning: ${family} cannot achieve WCAG AA contrast as text on white background. Using ${family}${darkestAvailable} as best effort.`,
				)
			}
		}
	} else {
		// For regular colors, find accessible shade for text on white background
		const accessibleLightShades = ['700', '800', '900', '600', '500']

		for (const testShade of accessibleLightShades) {
			const testKey = `${family}-${testShade}`
			if (flatColors[testKey]) {
				const testColor = toShortHex(flatColors[testKey])
				// Check if this shade is accessible as text ON white background
				if (isAccessible('#ffffff', testColor)) {
					accessibleLightColorVar = `${family}${testShade}`
					break
				}
			}
		}
	}

	// DARK MODE: --neo-theme-colorAccessible (text/border color ON dark page background)
	// Start with 200, go lighter (100) or darker (300, 400) if not accessible on black
	const accessibleDarkShades = ['200', '100', '300', '400', '500']
	let accessibleDarkColorVar = darkModeColorVar

	for (const testShade of accessibleDarkShades) {
		const testKey = `${family}-${testShade}`
		if (flatColors[testKey]) {
			const testColor = toShortHex(flatColors[testKey])
			// Check if this shade is accessible as text ON black background
			if (isAccessible('#000000', testColor)) {
				accessibleDarkColorVar = `${family}${testShade}`
				break
			}
		}
	}

	// Special case: black inverts in dark mode (black background → white background)
	// This allows black-colored components to gracefully flip to white when inside a dark context
	if (family === 'black') {
		darkModeColorVar = 'white'
		accessibleDarkColorVar = 'white'
	}

	// Text colors: white for most colors, black for exceptions
	const textColor = usesBlackTextInLightMode ? 'black' : 'white'

	// Determine the accent shade (200) for this color family - used for subtle accents/focus
	const accentShade = '200'
	const accentColorKey = `${family}-${accentShade}`
	const hasAccent = flatColors[accentColorKey] !== undefined
	const accentColorVar = hasAccent ? `${family}${accentShade}` : lightModeColorVar // e.g., "blue200"

	// Determine shade 100 for filled variant backgrounds in light mode
	const fillLightShade = '100'
	const fillLightColorKey = `${family}-${fillLightShade}`
	const hasFillLight = flatColors[fillLightColorKey] !== undefined
	const fillLightColorVar = hasFillLight ? `${family}${fillLightShade}` : accentColorVar // e.g., "blue100", fallback to accent

	// Determine shade 900 for filled variant backgrounds in dark mode
	const fillDarkShade = '900'
	const fillDarkColorKey = `${family}-${fillDarkShade}`
	const hasFillDark = flatColors[fillDarkColorKey] !== undefined
	const fillDarkColorVar = hasFillDark ? `${family}${fillDarkShade}` : lightModeColorVar // e.g., "blue900"

	// Generate class using just the family name (no shade number)
	const className = family // e.g., "blue" not "blue500"

	// Generate the CSS class with onDark support
	themedClasses.push(
		`.Themed--${className} {
	--neo-theme-color: var(--neo-color-${lightModeColorVar});
	--neo-theme-colorText: var(--neo-color-${textColor});
	--neo-theme-colorAccent: var(--neo-color-${accentColorVar});
	--neo-theme-colorAccessible: var(--neo-color-${accessibleLightColorVar});
	--neo-theme-colorFilledBg: var(--neo-color-${fillLightColorVar});
	--neo-theme-colorFilledBgDark: var(--neo-color-${fillDarkColorVar});

	@mixin onDark {
		--neo-theme-color: var(--neo-color-${darkModeColorVar});
		--neo-theme-colorText: var(--neo-color-black);
		--neo-theme-colorAccent: var(--neo-color-${accentColorVar});
		--neo-theme-colorAccessible: var(--neo-color-${accessibleDarkColorVar});
		--neo-theme-colorFilledBg: var(--neo-color-${fillLightColorVar});
		--neo-theme-colorFilledBgDark: var(--neo-color-${fillDarkColorVar});
	}
}`,
	)
})

// Write CSS variables and themed classes
writeFileSync(
	'./src/assets/styles/colors.css',
	`/**
 * --------------------------------------------------------------------
 * THIS FILE IS AUTO-GENERATED — DO NOT EDIT IT DIRECTLY!
 *
 * This file was generated by the generate-colors script.
 * Any manual changes will be overwritten.
 *
 * To update this file, run the appropriate generation script.
 * --------------------------------------------------------------------
 */

/* Color CSS Variables */
:root {
${cssVars}
}

/* Themed Color Classes */
/* Each color family has ONE class that automatically provides shades for different use cases */
/* Usage in components: class="Themed--blue" */
/* Variables provided: */
/*   --neo-theme-color: Main color (shade 500 on light, 400 on dark) */
/*   --neo-theme-colorText: Text color for use ON the main color (black/white based on WCAG) */
/*   --neo-theme-colorAccent: Subtle accent color (shade 200) for focus states */
/*   --neo-theme-colorAccessible: Accessible color for text/borders ON page background (shade 700 on light, 200 on dark) */
/*   --neo-theme-colorFilledBg: Subtle filled background color (shade 100) for filled/primary variant components */
/*   --neo-theme-colorFilledBgDark: Dark filled background color (shade 900) for filled/primary variant in dark mode */
${themedClasses.join('\n\n')}
`,
)

console.log('✅ colors.css generated')

runScript('npx prettier --write src/assets/styles/colors.css')

/**
 * Generate MD documentation
 */

const mdRowsArr: string[] = []

Object.entries(colorsRaw).forEach(([colorName, shades]) => {
	if (typeof shades === 'object') {
		Object.entries(shades as object)
			.filter(([shade]) => !Number.isNaN(Number(shade)))
			.forEach(([shade]) => {
				mdRowsArr.push(`| ${colorName} | ${shade} | \`--neo-color-${colorName}${shade}\` |`)
			})
	} else if (typeof shades === 'string') {
		mdRowsArr.push(`| ${colorName} | - | \`--neo-color-${colorName.replace('-', '')}\` |`)
	}
})

const mdHeader = `# Material Colors

> Auto-generated documentation of available CSS variables for colors.

| Color | Shade | CSS Variable |
|-------|-------|--------------|
`

const mdContent = `${mdHeader}${mdRowsArr.join('\n')}\n`

const mdFilePath = join(process.cwd(), 'docs/colors.md')
mkdirSync(dirname(mdFilePath), { recursive: true })
writeFileSync(mdFilePath, mdContent)
console.log('✅ Colors.md generated')

/**
 * Generate MDX file out of MD content
 */

const lines = mdContent.split('\n').filter((line) => line.trim().startsWith('|')) // skip header & separator
const rows = lines.slice(2) // skip table header + --- separator

type ColorName = (typeof colorNames)[number]

const dataByColorName: Record<ColorName | 'special', string[]> = Object.fromEntries(
	[...colorNames, 'special'].map((c) => [c, []]),
) as Record<ColorName, string[]>

// Build MDX table rows
rows.forEach((line) => {
	const data = line
		.split('|')
		.map((c) => c.trim())
		.filter((value) => value)

	let name = data[0]
	const value = data[2]

	if (specialColors.includes(name)) {
		name = 'special'
	}

	dataByColorName[name].push(`
			<tr>
				<td>${value}</td>
				<td>
					<div style={{
						display: 'flex',
						justifyContent: 'center',
						alignItems: 'center',

						inlineSize: '4rem',
						blockSize: '4rem',
						margin: 'auto',

						backgroundColor: \`var(${value.replace(/`/g, '')})\`,
						border: '1px solid var(--docs-color-border)'
					}}/>
				</td>
			</tr>
		`)
})

const tables = Object.entries(dataByColorName)
	.filter(([colorName, tableData]) => tableData.length && !specialColors.includes(colorName))
	.map(
		([color, tableData]) => `
<div style={{inlineSize: '100%'}}>
	<h2>${toPascalCase(color)}</h2>
	<table style={{inlineSize: '100%'}}>
		<thead>
			<tr>
				<th>Name</th>
				<th>Preview</th>
			</tr>
		</thead>
		<tbody>
			${tableData.join('')}
		</tbody>
	</table>
</div>
`,
	)

const mdxContent = `
import { Meta, Title, Subtitle } from '@storybook/addon-docs/blocks'

<Meta title="Foundation/Colors" />

<Title>Colors</Title>

{/**
 * --------------------------------------------------------------------
 * THIS FILE IS AUTO-GENERATED — DO NOT EDIT IT DIRECTLY!
 *
 * This file was generated by the generate-colors script.
 * Any manual changes will be overwritten.
 *
 * To update this file, run the appropriate generation script.
 * The script is automatically triggered by the pre-flight script
 * --------------------------------------------------------------------
 */}

<Subtitle>Material Design color palette with automatic accessibility optimization</Subtitle>

## How Theme Colors Work

When you apply a color to a component (e.g., \`color="blue"\`), the theme system provides:

- **\`--neo-theme-color\`**: Main background color
- **\`--neo-theme-colorText\`**: Text color for use ON the main color (auto-selected for WCAG AA compliance)
- **\`--neo-theme-colorAccent\`**: Subtle accent color (shade 200) for focus states
- **\`--neo-theme-colorAccessible\`**: Accessible color for text/borders ON page backgrounds

### Accessibility Strategy

**Light Mode (on white/light backgrounds):**
- Most colors use **white text** on a darker shade (automatically selected starting from 500)
- **Yellow, Amber, Orange** use **black text** on shade 500 for proper contrast

**Dark Mode (on black/dark backgrounds):**
- All colors use **black text** on a lighter shade (automatically selected starting from 500)

All color combinations are tested to meet **WCAG AA** contrast requirements (4.5:1 for normal text).

<div style={{
	padding: '16px',
	marginBlock: '24px',
	backgroundColor: 'var(--docs-color-bg-warning)',
	border: '1px solid var(--docs-color-border-warning)',
	borderRadius: '4px'
}}>
	<strong>⚠️ Special Colors:</strong> Yellow, Amber, and Orange use black text on their colored surface (buttons, badges) because they are too bright for white text. Avoid using them as text or link colors on light page backgrounds — they do not meet WCAG AA contrast against white.
</div>

## Available Colors

<div style={{display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(300px, 1fr))'}}>
	${tables.join('').replace(/\<\/table\>\n,/g, '<\/table\>')}
</div>
`

mkdirSync('./src/components/00-foundations', { recursive: true })
writeFileSync(`./src/components/00-foundations/colors.mdx`, mdxContent)
console.log(`✅ Storybook MDX generated`)

// Update cache after successful generation
updateCache(SCRIPT_NAME, SOURCE_FILES)
